filename=beamer_sample.tex

all: $(filename)
	pdflatex $(filename)

clean:
	rm $(filename).aux $(filename).log $(filename).nav $(filename).out $(filename).pdf $(filename).snm $(filename).toc $(filename).vrb
